### ISSUE TITLE
Angular 2 CLI option

### ISSUE THREAD

**Issue by josh-lester** [DarqueWarrior/generator-vsts#1]
I know that it would be fairly simple to add in the angular 2 quickstart project. But what are we looking at to be able to add an option for the angular cli? I tried this out manually but i am not sure where the dist folder gets created or where to grab it from to deploy to azure. Was trying not to check the dist folder into source control.

Also not sure if you would want this added since the cli project is still in beta.

**Comment by DarqueWarrior** [comment]
Thanks for the interest in helping.

I think I would prefer items that are released. However, we have to start at some point.  My goal is a user would be able to select any language and have the following:
- Complete project
- Unit tests
- Code coverage
- Build definition for VSTS
- Release definition for VSTS

No matter which of the three original languages you pick you get the exact same project as a starting point. I would like to keep with that trend but of course a CLI would have to be different.  I would like it to be more interesting than just hello world if possible so people can use them as templates of best practices.

I am willing to work to help get the CI/CD pipeline figured out. I just don't have the time to learn every language under the sun.  But I am confident that as a community project we can get the lion share.  This generator can make getting started with DevOps as easy as possible.
