### ISSUE TITLE
Local repo not created correctly on clean machine

### ISSUE THREAD

**Issue by brianrandell** [DarqueWarrior/generator-vsts#5]
Create a Server 2012 R2 VM in Azure.
Install tooling (Git for Windows, Node, and Yo).
Install and run YO VSTS.
Create a demo (ASP.NET for example).
Once done notice how it says you can just push.
Change to directory where repo should be.
Git status will tell you no repo.

Issue seems to be with Git not being correctly initialized on the machine.

**Comment by DarqueWarrior** [comment]
I need to test this and see if I can add better error messages to make this clear.

**Comment by DarqueWarrior** [comment]
Yo team has a fix for this. Yo team should be used instead of yo VSTS as this project is no longer maintained.
