### ISSUE TITLE
ASP.NET project fails to build in VS Code

### ISSUE THREAD

**Issue by brianrandell** [DarqueWarrior/generator-vsts#6]
Use YO VSTS to create an ASP.NET demo.
Once done open the folder in VS Code.
Follow prompts to restore, etc.

Error:
MSBUILD : error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1. [c:\yovsts\yoaspnet3\src\yoaspnet3\project.json]
Done: 1.

Related: dotnet build at command prompt doesn't work
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

VS Code 1.7.2
C# Ext 1.5.3

**Comment by DarqueWarrior** [comment]
That is very strange that it works on the build clients but not locally. Trying to figure this out.

**Comment by DarqueWarrior** [comment]
I will upgrade to csproj format after my session on Wednesday. It currently works on hosted but not local.

**Comment by DarqueWarrior** [comment]
I have postponed this change until VSTS hosted build agents support csproj. This feature will be added to yo Team as this project is no longer maintained.
